# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class UserMergeUser(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        UserMergeUser - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'project': 'str',
            'user': 'str',
            'api': 'UserContext',
            'anonymous_id': 'str',
            'created_at': 'datetime',
            'merged_at': 'datetime'
        }

        self.attribute_map = {
            'project': 'project',
            'user': 'user',
            'api': 'api',
            'anonymous_id': 'anonymous_id',
            'created_at': 'created_at',
            'merged_at': 'merged_at'
        }

        self._project = None
        self._user = None
        self._api = None
        self._anonymous_id = None
        self._created_at = None
        self._merged_at = None

    @property
    def project(self):
        """
        Gets the project of this UserMergeUser.


        :return: The project of this UserMergeUser.
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """
        Sets the project of this UserMergeUser.


        :param project: The project of this UserMergeUser.
        :type: str
        """
        self._project = project

    @property
    def user(self):
        """
        Gets the user of this UserMergeUser.


        :return: The user of this UserMergeUser.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """
        Sets the user of this UserMergeUser.


        :param user: The user of this UserMergeUser.
        :type: str
        """
        self._user = user

    @property
    def api(self):
        """
        Gets the api of this UserMergeUser.


        :return: The api of this UserMergeUser.
        :rtype: UserContext
        """
        return self._api

    @api.setter
    def api(self, api):
        """
        Sets the api of this UserMergeUser.


        :param api: The api of this UserMergeUser.
        :type: UserContext
        """
        self._api = api

    @property
    def anonymous_id(self):
        """
        Gets the anonymous_id of this UserMergeUser.


        :return: The anonymous_id of this UserMergeUser.
        :rtype: str
        """
        return self._anonymous_id

    @anonymous_id.setter
    def anonymous_id(self, anonymous_id):
        """
        Sets the anonymous_id of this UserMergeUser.


        :param anonymous_id: The anonymous_id of this UserMergeUser.
        :type: str
        """
        self._anonymous_id = anonymous_id

    @property
    def created_at(self):
        """
        Gets the created_at of this UserMergeUser.


        :return: The created_at of this UserMergeUser.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this UserMergeUser.


        :param created_at: The created_at of this UserMergeUser.
        :type: datetime
        """
        self._created_at = created_at

    @property
    def merged_at(self):
        """
        Gets the merged_at of this UserMergeUser.


        :return: The merged_at of this UserMergeUser.
        :rtype: datetime
        """
        return self._merged_at

    @merged_at.setter
    def merged_at(self, merged_at):
        """
        Sets the merged_at of this UserMergeUser.


        :param merged_at: The merged_at of this UserMergeUser.
        :type: datetime
        """
        self._merged_at = merged_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

