//
// ContinuousQueryBuilder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ContinuousQueryBuilder: JSONEncodable {

    public var name: String?
    public var query: String?
    public var collections: [String]?
    public var options: [String:String]?
    public var tableName: String?
    public var partitionKeys: [String]?
    

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["query"] = self.query
        nillableDictionary["collections"] = self.collections?.encodeToJSON()
        nillableDictionary["options"] = self.options?.encodeToJSON()
        nillableDictionary["tableName"] = self.tableName
        nillableDictionary["partitionKeys"] = self.partitionKeys?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
