//
// EventFilterAggregation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EventFilterAggregation: JSONEncodable {

    public enum SwaggerType: String { 
        case Count = "COUNT"
        case CountUnique = "COUNT_UNIQUE"
        case Sum = "SUM"
        case Minimum = "MINIMUM"
        case Maximum = "MAXIMUM"
        case Average = "AVERAGE"
        case ApproximateUnique = "APPROXIMATE_UNIQUE"
    }
    
    public var field: String?
    public var minimum: Int?
    public var maximum: Int?
    public var type: SwaggerType?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["field"] = self.field
        nillableDictionary["minimum"] = self.minimum
        nillableDictionary["maximum"] = self.maximum
        nillableDictionary["type"] = self.type?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
