//
// QueryResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class QueryResult: JSONEncodable {

    public var metadata: [SchemaField]?
    public var result: [[String]]?
    public var error: QueryError?
    public var properties: [String:String]?
    public var failed: Bool?
    

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["metadata"] = self.metadata?.encodeToJSON()
        nillableDictionary["result"] = self.result?.encodeToJSON()
        nillableDictionary["error"] = self.error?.encodeToJSON()
        nillableDictionary["properties"] = self.properties?.encodeToJSON()
        nillableDictionary["failed"] = self.failed
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
