//
// RealTimeQueryResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RealTimeQueryResult: JSONEncodable {

    public var start: Int?
    public var end: Int?
    public var result: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["start"] = self.start
        nillableDictionary["end"] = self.end
        nillableDictionary["result"] = self.result
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
