//
// SerializableAction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SerializableAction: JSONEncodable {

    public enum SwaggerType: String { 
        case Client = "client"
        case User_action = "user_action"
        case Event = "event"
    }
    
    public var type: SwaggerType?
    public var value: String?
    

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["value"] = self.value
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
