//
// Threshold.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Threshold: JSONEncodable {

    public enum Aggregation: String { 
        case Count = "count"
        case Sum = "sum"
    }
    
    public var aggregation: Aggregation?
    public var fieldName: String?
    public var value: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["aggregation"] = self.aggregation?.rawValue
        nillableDictionary["fieldName"] = self.fieldName
        nillableDictionary["value"] = self.value
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
