//
// User_UnsetProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class User_UnsetProperty: JSONEncodable {

    public var project: String?
    public var api: UserContext?
    public var user: String?
    public var property: [String]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["project"] = self.project
        nillableDictionary["api"] = self.api?.encodeToJSON()
        nillableDictionary["user"] = self.user
        nillableDictionary["property"] = self.property?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
