//
// User_MergeUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class User_MergeUser: JSONEncodable {

    public var project: String?
    public var user: String?
    public var api: UserContext?
    public var anonymous_id: String?
    public var created_at: NSDate?
    public var merged_at: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["project"] = self.project
        nillableDictionary["user"] = self.user
        nillableDictionary["api"] = self.api?.encodeToJSON()
        nillableDictionary["anonymous_id"] = self.anonymous_id
        nillableDictionary["created_at"] = self.created_at?.encodeToJSON()
        nillableDictionary["merged_at"] = self.merged_at?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
